### PR TITLE
Added OH logo and git logo

### PR DESCRIPTION
**Pull request by jainarya**
Change the construction gifs to the Open Hatch logo and Git logo. For issue #1

### CODE REVIEW

**Comment by ahueniken** [comment]
@jainarya you added the new images in the html but you also need to add the images to the repository. When in terminal or git bash type git status and it will likely have two red lines with the image names. To add all the changed files to a repository type: git add .
The period adds all changed files. Then commit, push and update the pull request.

Come find me if this is confusing :)

**Comment by jainarya** [comment]
Sorry! Do I create a new PR now?

**Comment by ahueniken** [comment]
No need it added them automatically :)

**Comment by ahueniken** [comment]
Accepted the PR. Thanks!

**Pull request merged**
